Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-11, with the labels that each got.

#558 Avoid assuming where the RCP column is when adjusting scenario spec
  src/ecosystem/Ecosystem.jl
  src/io/result_io.jl
Labels: bug

#555 Coral cover consistently represented as relative to coral habitable area
  examples/Example_domain/site_data/coral_cover.nc
  src/ADRIA.jl
  src/Domain.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/ExtInterface/ReefMod/Domain.jl
  src/decision/dMCDA.jl
  src/decision/location_selection.jl
  src/ecosystem/connectivity.jl
  src/ecosystem/corals/CoralGrowth.jl
  src/ecosystem/corals/growth.jl
  src/interventions/seeding.jl
  src/io/ResultSet.jl
  src/io/inputs.jl
  src/io/result_io.jl
  src/metrics/metrics.jl
  src/metrics/performance.jl
  src/metrics/scenario.jl
  src/metrics/site_level.jl
  src/scenario.jl
  test/data/test_init_coral_cover.csv
  test/growth.jl
  test/mcda.jl
  test/metrics.jl
  test/runtests.jl
  test/seeding.jl
  test/site_selection.jl
Labels: enhancement

#576 Prevent test_rs() from creating tmp dir inside test/data
  test/runtests.jl
Labels: maintenance

#570 Visualizations to be agnostic to Makie backend
  Aviz/build/precompile_script.jl
  Project.toml
  docs/src/usage/analysis.md
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/viz/sensitivity.jl
  ext/AvizExt/viz/spatial.jl
  ext/AvizExt/viz/viz.jl
Labels: maintenance

#579 Apply blue styleguide to some files
  src/Domain.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/ExtInterface/ReefMod/Domain.jl
  src/ecosystem/Ecosystem.jl
  src/ecosystem/connectivity.jl
  src/ecosystem/const_params.jl
  src/ecosystem/waves.jl
  src/interventions/Interventions.jl
  src/interventions/fogging.jl
  src/interventions/seeding.jl
  src/io/inputs.jl
Labels: maintenance

#581 Update use of progress meter to resolve deprecation warning
  src/scenario.jl
Labels: bug

#552 Add ability to perform convergence analysis
  docs/src/assets/imgs/colormap_convergence_components.png
  docs/src/assets/imgs/colormap_convergence_factors.png
  docs/src/assets/imgs/colormap_convergence_factors_lines.png
  docs/src/assets/imgs/colormap_convergence_factors_lines_overlay.png
  docs/src/usage/analysis.md
  ext/AvizExt/viz/scenarios.jl
  ext/AvizExt/viz/sensitivity.jl
  src/analysis/sensitivity.jl
  src/viz/viz.jl
Labels: enhancement

#573 Add separate weighting parameter for depth criteria
  examples/example_scenarios.csv
  src/decision/CriteriaWeights.jl
  src/decision/dMCDA.jl
  test/growth.jl
  test/mcda.jl
Labels: enhancement

#583 Replace package NCDatasets by NetCDF
  Project.toml
  src/Domain.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/io/inputs.jl
  test/data/test_ncdf_char.nc
  test/io/inputs.jl
  test/runtests.jl
Labels: maintenance

#574 Add conversion to scientific notation
  ext/AvizExt/theme.jl
  ext/AvizExt/viz/clustering.jl
  src/analysis/scenario.jl
  src/utils/text_display.jl
  test/runtests.jl
  test/utils/text_display.jl
Labels: enhancement

#593 Change approach to listing supported MCDA methods
  ext/AvizExt/viz/sensitivity.jl
  src/decision/dMCDA.jl
  src/interventions/Interventions.jl
  test/site_selection.jl
Labels: maintenance

#607 Fix proportional_adjustment vector conversion computational error
  src/ecosystem/corals/growth.jl
  test/growth.jl
Labels: bug

#601 Fix treatment of categorical factors in regional sensitivity analysis
  ext/AvizExt/viz/sensitivity.jl
  src/analysis/sensitivity.jl
  src/io/result_io.jl
Labels: bug

#598 Deactivated interventions should be considered separately
  examples/example_scenarios.csv
  ext/AvizExt/viz/rule_extraction.jl
  ext/AvizExt/viz/sensitivity.jl
  src/decision/dMCDA.jl
  src/interventions/Interventions.jl
  src/io/sampling.jl
  src/metrics/performance.jl
  src/scenario.jl
  test/site_selection.jl
Labels: maintenance

#612 Adjust language in architectural overview to match recent changes
  docs/src/architecture/architecture.md
Labels: documentation, maintenance
