Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-09, with the labels that each got.

#444 Fix print_rules adding & when there are two clauses
  src/analysis/rule_extraction.jl
Labels: bug

#422 Implement rule scatter plot function
  ext/AvizExt/viz/rule_extraction.jl
  ext/AvizExt/viz/sensitivity.jl
  ext/AvizExt/viz/viz.jl
  src/viz/viz.jl
Labels: enhancement

#429 Documentation improvement
  docs/Manifest.toml
  docs/make.jl
  docs/src/API.md
  docs/src/architecture/architecture.md
  docs/src/architecture/domain_and_resultsets.md
  docs/src/assets/imgs/aviz_scenario.png
  docs/src/assets/imgs/outcome_map.png
  docs/src/assets/imgs/pawn_si.png
  docs/src/assets/imgs/rsa.png
  docs/src/assets/imgs/scens.png
  docs/src/assets/imgs/tsa.png
  docs/src/assets/imgs/tsc_map.png
  docs/src/development/development_setup.md
  docs/src/index.md
  docs/src/overview.md
  docs/src/usage/analysis.md
  docs/src/usage/cookbook.md
  docs/src/usage/domain.md
  docs/src/usage/getting_started.md
  docs/src/usage/scenario_generation.md
  src/ExtInterface/ReefMod/Domain.jl
  src/metrics/metrics.jl
Labels: documentation

#457 Changes to improve performance of PAWN sensitivity analysis
  ext/AvizExt/analysis.jl
  src/analysis/sensitivity.jl
Labels: bug

#460 Fix print_rules condition
  src/analysis/rule_extraction.jl
Labels: bug

#461 Update ADRIA logo
  assets/imgs/ADRIA_logo.png
  docs/src/assets/logo.png
Labels: enhancement

#462 Adjust PAWN function to support 1D matrix for convenience
  src/analysis/sensitivity.jl
Labels: documentation, enhancement

#468 Include rule_extraction.jl in viz.jl
  ext/AvizExt/viz/viz.jl
Labels: enhancement

#467 Add new cluster_rules method that accepts BitVector or Vector{Bool}
  src/analysis/rule_extraction.jl
Labels: enhancement

#469 Precompilation reduction
  LocalPreferences.toml
  ODE_preferences.jl
  Project.toml
  src/ADRIA.jl
  src/ecosystem/Ecosystem.jl
  src/ecosystem/connectivity.jl
  src/ecosystem/const_params.jl
  src/ecosystem/corals/growth.jl
  src/io/ResultSet.jl
  src/io/sampling.jl
  src/utils/setup.jl
  src/utils/text_display.jl
Labels: enhancement

#471 Update sensitivity module to follow Blue style
  src/analysis/sensitivity.jl
Labels: maintenance

#472 Update Doc mentioning blue style guide
  docs/src/development/development_setup.md
Labels: documentation, maintenance

#475 Update viz.rules_scatter to accept targeted clusters
  ext/AvizExt/viz/rule_extraction.jl
Labels: enhancement

#479 Remove locations with no space from consideration for interventions
  src/decision/dMCDA.jl
Labels: bug

#478 Rename time_series_clustering and ts_cluster
  docs/src/usage/analysis.md
  ext/AvizExt/viz/clustering.jl
  src/analysis/clustering.jl
  src/viz/viz.jl
  test/clustering.jl
Labels: maintenance

#485 Consistent treatment of k area on data load
  src/Domain.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/ExtInterface/ReefMod/Domain.jl
Labels: maintenance

#486 Transform ICC from relative to absolute area to relative to k area
  src/Domain.jl
  src/ExtInterface/ReefMod/Domain.jl
  src/io/inputs.jl
  src/scenario.jl
Labels: maintenance

#442 Fix duplicate x-axis values bug in `viz.outcome_map()`
  ext/AvizExt/viz/sensitivity.jl
  src/analysis/sensitivity.jl
Labels: bug

#477 Add Documentation Sensitivity section for Rule Induction algorithm
  docs/Manifest.toml
  docs/src/assets/imgs/rules_scatter.png
  docs/src/usage/analysis.md
  src/analysis/clustering.jl
Labels: documentation, maintenance

#499 Add .JuliaFormatter.toml to .gitignore
  .gitignore
Labels: maintenance

#476 Deprecate `run_scenarios(scens, dom, ...)`
  build/precompile_script.jl
  docs/src/usage/analysis.md
  docs/src/usage/cookbook.md
  docs/src/usage/getting_started.md
  docs/src/usage/scenario_discovery.md
  docs/src/usage/scenario_runs.md
  examples/example_scenarios.csv
  examples/running_scenarios.jl
  examples/sampling_scenarios.jl
  ext/AvizExt/AvizExt.jl
  src/ADRIA.jl
  src/analysis/sensitivity.jl
  src/main_app.jl
  src/scenario.jl
  test/example_run.jl
  test/runtests.jl
Labels: maintenance

#496 Fix _time_labels missing last label
  ext/AvizExt/viz/viz.jl
Labels: bug

#500 Refactor viz.scenario
  docs/src/usage/analysis.md
  docs/src/usage/getting_started.md
  ext/AvizExt/viz/scenario.jl
  ext/AvizExt/viz/scenarios.jl
  ext/AvizExt/viz/viz.jl
  src/viz/viz.jl
Labels: maintenance

#506 Update CSV.write writeheader parameter to header
  src/Domain.jl
Labels: maintenance

#511 Fix bug causing Domain loading with RCP to error
  src/ecosystem/Ecosystem.jl
Labels: bug
