Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-06, with the labels that each got.

#361 Update documentation
  Aviz/README.md
  README.md
  docs/Manifest.toml
  docs/src/architecture/domain_and_resultsets.md
  docs/src/assets/imgs/ADRIA_Input_Output_diagram.png
  docs/src/assets/imgs/aviz_app.png
  docs/src/assets/imgs/aviz_scenario.png
  docs/src/assets/imgs/outcome_map.png
  docs/src/assets/imgs/pawn_si.png
  docs/src/assets/imgs/rsa.png
  docs/src/assets/imgs/scens.png
  docs/src/assets/imgs/tsa.png
  docs/src/development/development_setup.md
  docs/src/overview.md
  docs/src/synopsis.md
  docs/src/usage/analysis.md
  docs/src/usage/domain.md
  docs/src/usage/getting_started.md
  docs/src/usage/scenario_generation.md
Labels: documentation

#365 Fix: Metric errors when applied to a single simulation
  src/io/ResultSet.jl
  src/io/sampling.jl
  src/metrics/metrics.jl
  src/metrics/scenario.jl
Labels: bug

#367 Address ranking errors in mcda outputs
  src/sites/dMCDA.jl
  test/site_selection.jl
Labels: bug

#370 Add temporal clustering
  Project.toml
  src/analysis/analysis.jl
  src/analysis/clustering.jl
  test/clustering.jl
  test/runtests.jl
Labels: enhancement

#371 Fix incorrect type check
  src/metrics/metrics.jl
Labels: bug

#374 Update time series clustering and add visualization functionality
  docs/src/assets/imgs/tsc.png
  docs/src/usage/analysis.md
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/viz.jl
  src/analysis/clustering.jl
  src/viz/viz.jl
Labels: enhancement

#376 Refactor run_scenarios to improve when running multiple rcps
  src/io/result_io.jl
  src/scenario.jl
  src/utils/setup.jl
Labels: enhancement
