Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-10, with the labels that each got.

#463 Add function to find robust scenarios across several metrics
  ext/AvizExt/viz/rule_extraction.jl
  src/analysis/analysis.jl
  src/analysis/clustering.jl
  src/metrics/metrics.jl
  src/metrics/scenario.jl
Labels: enhancement

#505 Add `:summary` option to `viz.scenarios`
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/scenarios.jl
  src/analysis/analysis.jl
Labels: enhancement

#523 Fix scenarios subsetting now working
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/theme.jl
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/scenarios.jl
  ext/AvizExt/viz/viz.jl
  src/analysis/analysis.jl
  src/analysis/scenario.jl
Labels: bug, enhancement

#491 Fix bug in how `sensitivity.outcome_map()` treats categorical variables.
  Project.toml
  ext/AvizExt/viz/sensitivity.jl
  src/Domain.jl
  src/analysis/analysis.jl
  src/analysis/sensitivity.jl
  src/decision/Criteria.jl
  src/ecosystem/Ecosystem.jl
  src/interventions/Interventions.jl
  src/io/inputs.jl
  src/io/result_io.jl
  src/io/sampling.jl
Labels: bug

#541 Add missing scenario analysis function definitions to analysis module
  src/analysis/analysis.jl
Labels: bug

#539 Broadcast _check_discrete inside update_params
  src/Domain.jl
  src/ecosystem/Ecosystem.jl
  src/io/inputs.jl
  test/data/test_scenarios.csv
  test/domain.jl
  test/metrics.jl
  test/runtests.jl
Labels: bug

#545 Update analysis docs with recent scenarios and clusters developments
  docs/src/assets/imgs/aviz_scenario.png
  docs/src/assets/imgs/scenarios_tac.png
  docs/src/assets/imgs/tsc.png
  docs/src/assets/imgs/tsc_asv.png
  docs/src/usage/analysis.md
  ext/AvizExt/viz/scenarios.jl
Labels: documentation, enhancement
