Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-08, with the labels that each got.

#407 Fix map display (default display when plotting Domain or ResultSet)
  ext/AvizExt/viz/spatial.jl
Labels: bug

#409 Fix excessive memory use (#405)
  src/ecosystem/corals/growth.jl
  src/scenario.jl
Labels: bug

#408 Update ReefMod interface to match new species list
  src/ADRIA.jl
  src/ExtInterface/ReefMod/Domain.jl
  src/ExtInterface/ReefMod/scenarios.jl
Labels: maintenance

#412 Small miscellaneous changes for scenario visualizations
  ext/AvizExt/theme.jl
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/scenario.jl
Labels: maintenance

#425 Fix unnecessarily squashed figure when plotting outcome map for 1 factor
  ext/AvizExt/viz/sensitivity.jl
Labels: bug

#424 Move and modify behaviour of target_cluster function
  src/analysis/clustering.jl
  src/analysis/rule_extraction.jl
Labels: enhancement

#416 Fix workers crashing and leaking memory when running scenarios in parallel
  src/ADRIA.jl
  src/ecosystem/corals/growth.jl
  src/interventions/seeding.jl
  src/io/result_io.jl
  src/scenario.jl
  src/utils/setup.jl
  test/seeding.jl
Labels: bug

#430 Fix scenario metrics with field :scenario instead of :scenarios
  src/metrics/scenario.jl
Labels: bug

#435 Address very slow extraction of relative cover values
  src/metrics/metrics.jl
Labels: enhancement

#439 Fix clustering map visualisation
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/spatial.jl
Labels: bug

#438 Fix loc_trajectory and per_loc function
  src/metrics/site_level.jl
Labels: bug

#443 Update SIRUS StableRules type
  src/analysis/rule_extraction.jl
Labels: bug

#441 Add Blue Style Guide badge to README
  README.md
Labels: documentation
