Repository open-AIMS/ADRIA.jl, pull requests merged in 2023-07, with the labels that each got.

#356 Add map visualization - displays k-area
  Project.toml
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/spatial.jl
  ext/AvizExt/viz/spatial.jl
  ext/AvizExt/viz/viz.jl
  src/io/result_io.jl
  src/metrics/metrics.jl
  src/metrics/site_level.jl
  src/viz/viz.jl
Labels: enhancement

#387 Consider near-term conditions with greater weight than far-future conditions
  src/scenario.jl
Labels: enhancement

#382 Temporal clustering for spatial data
  docs/src/assets/imgs/tsc_map.png
  docs/src/usage/analysis.md
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/spatial.jl
  src/analysis/clustering.jl
  src/metrics/site_level.jl
  src/viz/viz.jl
Labels: enhancement

#381 Distribution-based bleaching mortality to capture natural adaptation and heritability
  Project.toml
  ext/AvizExt/theme.jl
  ext/AvizExt/viz/sensitivity.jl
  src/ADRIA.jl
  src/Domain.jl
  src/analysis/pareto.jl
  src/ecosystem/Ecosystem.jl
  src/ecosystem/corals/growth.jl
  src/ecosystem/corals/spec.jl
  src/ecosystem/waves.jl
  src/interventions/fogging.jl
  src/interventions/seeding.jl
  src/io/result_io.jl
  src/io/sampling.jl
  src/scenario.jl
  test/data/test_scenarios.csv
  test/growth.jl
  test/sampling.jl
  test/seeding.jl
  test/spec.jl
Labels: enhancement

#385 Remove duplicate function `recruitment`
  src/ecosystem/corals/growth.jl
  test/growth.jl
Labels: maintenance

#397 Fix bug: Use wave condition for current timestep, not previous
  src/scenario.jl
Labels: bug

#386 Reorganize package structure
  src/ADRIA.jl
  src/decision/Criteria.jl
  src/decision/dMCDA.jl
  src/decision/mcda_methods.jl
  src/ecosystem/Ecosystem.jl
  src/ecosystem/connectivity.jl
  src/ecosystem/corals/Corals.jl
  src/ecosystem/corals/spec.jl
  src/interventions/Interventions.jl
  test/growth.jl
  test/seeding.jl
Labels: maintenance

#400 Incorrect function being called
  src/metrics/site_level.jl
Labels: bug
