Repository open-AIMS/ADRIA.jl, pull requests merged in 2024-08, with the labels that each got.

#814 Fix sampling test
  test/sampling.jl
Labels: chore

#817 Apply changes to ADRIA to make it compatible with CoralBlox model
  Project.toml
  ext/AvizExt/theme.jl
  src/ADRIA.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/ExtInterface/ReefMod/RMEDomain.jl
  src/ExtInterface/ReefMod/ReefModDomain.jl
  src/analysis/analysis.jl
  src/analysis/clustering.jl
  src/analysis/intervention.jl
  src/analysis/pareto.jl
  src/analysis/sensitivity.jl
  src/decision/Criteria/DecisionPreferences.jl
  src/decision/Criteria/SeedCriteria.jl
  src/decision/location_selection.jl
  src/ecosystem/Ecosystem.jl
  src/ecosystem/corals/CoralGrowth.jl
  src/ecosystem/corals/Corals.jl
  src/ecosystem/corals/growth.jl
  src/factors/const_params.jl
  src/interventions/Interventions.jl
  src/interventions/seeding.jl
  src/io/datacubes.jl
  src/io/initial_coral_cover.jl
  src/io/inputs.jl
  src/io/result_io.jl
  src/io/sampling.jl
  src/metrics/metrics.jl
  src/scenario.jl
  src/utils/scale.jl
  test/data/Test_domain/datapackage.json
  test/data/Test_domain/spatial/coral_cover.nc
  test/data_loading.jl
  test/growth.jl
  test/mcda.jl
  test/metrics.jl
  test/runtests.jl
  test/seeding.jl
  test/utils/scale.jl
Labels: enhancement, breaking change

#827 Add reshape to fix dimension mismatch when logging dhw tolerances
  src/scenario.jl
Labels: bug

#831 Rename metrics `:sites` dimension with `:locations`
  docs/src/development/metrics.md
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/spatial.jl
  src/ADRIA.jl
  src/Domain.jl
  src/ExtInterface/ADRIA/Domain.jl
  src/ExtInterface/ReefMod/RMEDomain.jl
  src/ExtInterface/ReefMod/ReefModDomain.jl
  src/analysis/intervention.jl
  src/decision/Criteria/SeedCriteria.jl
  src/decision/dMCDA.jl
  src/decision/location_selection.jl
  src/ecosystem/connectivity.jl
  src/ecosystem/corals/CoralGrowth.jl
  src/ecosystem/corals/growth.jl
  src/ecosystem/corals/growth_expanded.jl
  src/io/ResultSet.jl
  src/io/initial_coral_cover.jl
  src/io/inputs.jl
  src/io/result_io.jl
  src/io/rme_result_io.jl
  src/metrics/metrics.jl
  src/metrics/ranks.jl
  src/metrics/reef_indices.jl
  src/metrics/scenario.jl
  src/metrics/site_level.jl
  src/metrics/temporal.jl
  src/metrics/utils.jl
  src/scenario.jl
  src/spatial/spatial.jl
  test/connectivity.jl
  test/data_loading.jl
  test/growth.jl
  test/metrics.jl
  test/seeding.jl
  test/site_selection.jl
  test/spatial_clustering.jl
Labels: chore
