Repository open-AIMS/ADRIA.jl, pull requests merged in 2024-06, with the labels that each got.

#773 Fix erroneous function call in docstrings
  src/decision/location_selection.jl
Labels: documentation

#770 Change assisted adaptation to a Discrete Uniform value
  src/interventions/Interventions.jl
Labels: maintenance

#771 Use underlying data instead of YAXArray type
  ext/AvizExt/viz/environment/dhw.jl
Labels: maintenance

#778 Fix mismatched function name in docstring
  ext/AvizExt/viz/spatial.jl
Labels: documentation

#782 Fix site_level dosctring
  src/metrics/site_level.jl
Labels: documentation, maintenance

#774 Add methods to extract deployment location info
  src/decision/location_selection.jl
Labels: enhancement

#772 Increase compression level for ResultSet
  src/io/ResultSet.jl
Labels: maintenance

#776 Clean up defunct dependencies
  Project.toml
  src/ADRIA.jl
  src/Domain.jl
  src/decision/dMCDA.jl
  src/io/sampling.jl
  src/scenario.jl
  test/aqua.jl
  test/runtests.jl
Labels: maintenance

#787 Add default option to _sort_keys
  ext/AvizExt/viz/clustering.jl
  ext/AvizExt/viz/scenarios.jl
Labels: enhancement

#786 Assortment of improvements to SIRUS and Time Series Clustering
  ext/AvizExt/theme.jl
  ext/AvizExt/viz/scenarios.jl
  src/analysis/clustering.jl
  src/analysis/rule_extraction.jl
Labels: enhancement
