Repository open-AIMS/ADRIA.jl, pull requests merged in 2024-03, with the labels that each got.

#716 Keep metadata in results
  src/decision/dMCDA.jl
  src/metrics/metrics.jl
Labels: bug

#717 Finalize update of standalone MCDA methods
  src/decision/location_selection.jl
Labels: breaking change

#720 Provide a succinct overview of MCDA
  docs/src/dMCDA.md
Labels: documentation

#722 Add support to cyclone mortality to ReefModDomain
  src/ExtInterface/ReefMod/ReefModDomain.jl
Labels: enhancement
