Repository open-AIMS/ADRIA.jl, pull requests merged in 2024-07, with the labels that each got.

#798 Minor updates to geospatial functions/handling
  Project.toml
  docs/src/usage/analysis.md
  ext/AvizExt/AvizExt.jl
  ext/AvizExt/viz/location_selection.jl
  ext/AvizExt/viz/spatial.jl
  ext/AvizExt/viz/taxa_dynamics.jl
  ext/AvizExt/viz/viz.jl
  src/ADRIA.jl
  src/io/result_io.jl
  src/spatial/spatial.jl
  test/data/Test_domain/spatial/Test_domain.gpkg
  test/data/test_site_data.gpkg
  test/runtests.jl
Labels: documentation, maintenance

#805 Use CoralBlox linear_extension_scale_factor
  src/ADRIA.jl
  src/ecosystem/corals/Corals.jl
  src/ecosystem/corals/growth.jl
  src/scenario.jl
  src/utils/scale.jl
  test/runtests.jl
  test/utils/scale.jl
Labels: enhancement

#809 Fix broken tests
  ext/AvizExt/viz/scenarios.jl
  test/clustering.jl
Labels: bug
