Repository open-AIMS/ADRIA.jl, pull requests merged in 2025-04, with the labels that each got.

#939 Update docs to configure Julia Formatter extension
  .JuliaFormatter.toml
  docs/src/development/development_setup.md
Labels: documentation

#929 Replace and deprecate remaining use of `site_k_area`
  docs/src/usage/analysis.md
  src/ADRIA.jl
  src/Domain.jl
  src/decision/dMCDA.jl
  src/decision/location_selection.jl
  src/io/ResultSet.jl
  src/metrics/metrics.jl
  src/metrics/scenario.jl
  src/scenario.jl
  test/mcda.jl
  test/run_scenarios.jl
Labels: maintenance

#945 Fix docs build
  docs/Manifest.toml
  docs/src/assets/imgs/analysis/criteria_spatial_plots.png
  docs/src/usage/analysis.md
Labels: bug, documentation
